### ISSUE TITLE
Lista de revisão

### ISSUE THREAD

**Issue by Victor-Mag** [professorlineu/PRCE2-2019-2#1]
por favor, testar meu código! 
https://github.com/professorlineu/PRCE2-2019-2/tree/master/Atividades/Victor_Magalhaes/Revisao

**Comment by sbrohded** [comment]
Arquivo testado.  No exercício 25 do Cap5, quando é inserido um número negativo, ele calcula o rendimento, fazendo com que a divida do cliente aumente.

**Comment by sbrohded** [comment]
Arquivo testado. No exercício 25 do Cap5, quando é inserido um número negativo, ele calcula o rendimento, fazendo com que a divida do cliente aumente.
