### ISSUE TITLE
Teste lista Revisão

### ISSUE THREAD

**Issue by guilherme0170** [professorlineu/PRCE2-2019-2#9]
Alguém aí consegue testar os meus códigos da lista de revisão? Agradeço desde já.
Link: https://github.com/professorlineu/PRCE2-2019-2/tree/master/Atividades/Guilherme_Marques/Revisao

**Comment by sbrohded** [comment]
Fala Guilherme, beleza?

Segue os meus comentários:

Cap 4 Ex19: 

- Não aceita letra minuscula

Cap 4 Ex9:

- Aceita letras e informa que a letra é um saldo negativo.

Cap 5 Ex22:

- Não consigo diferenciar qual a sequência de digitação certa (Idade e Altura  ou Altura e Idade)

- No lugar do "é", aparece um "Ú"
![image](https://user-images.githubusercontent.com/53545042/65461096-a680e000-de29-11e9-8b64-abfc713dc2d4.png)

- Aceita números negativos e encerra o programa logo após

- Aceita letras e calcula de alguma forma não imaginária a altura média
 
![image](https://user-images.githubusercontent.com/53545042/65461280-ffe90f00-de29-11e9-91de-6189109bc3ea.png)
